version: "3.3"
services:
  back_end:
    build: back_end/.
    volumes:
      - ./back_end:/back_end
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      spring.datasource.url: "jdbc:mariadb://db/engineer_review"
      spring.datasource.username: "user"
      spring.datasource.password: "password"
      server.port: 8080
      server.address: 0.0.0.0
      spring.jpa.database-platform: "org.hibernate.dialect.MariaDB53Dialect"
      spring.jpa.hibernate.ddl-auto: "update"

  front_end:
    build: front_end/.
    volumes:
      - ./front_end:/front_end
    command: yarn start
    ports:
      - "3000:3000"
    stdin_open: true

  db:
    image: mariadb
    expose:
      - "3305"
    ports:
      - "3305:3305"
    environment:
      - MYSQL_DATABASE=engineer_review
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    volumes:
      - /sessions
