version: "3.3"
services:
  spring:
    build: spring/.
    volumes:
      - ..:/spring
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      spring.datasource.url: "jdbc:mariadb://db/engineer_review"
      spring.datasource.username: "user"
      spring.datasource.password: "password"
      server.port: 8080
      server.address: 0.0.0.0
      spring.jpa.database-platform: "org.hibernate.dialect.MariaDB53Dialect"
      spring.jpa.hibernate.ddl-auto: "update"

  react:
    build: react/.
    volumes:
      - ../:/usr/src/app
    ports:
      - "3000:3000"

  db:
    image: mariadb
    expose:
      - "3305"
    ports:
      - "3305:3305"
    environment:
      - MYSQL_DATABASE=engineer_review
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword,
